data_directory "/home/localadmin/Documents/Melina_branch/Sim_Growth"
repetitions 20
<capacities>
24
<\capacities>
<vox_sizes>
50
<\vox_sizes>
<icvf>
0.7
<\icvf>
<spheres_overlap_factors>
2
<\spheres_overlap_factors>
beading_variation 1
<END>